US616059 Multi-valued metadata support
FileAnalysisSuite/adaptersdk-impl-jaxrs pull request #13
Opened 2023-01-11 14:45 UTC by kploch

2023-01-11 14:47 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/FileAnalysisSuite/job/FileAnalysisSuite~adaptersdk-impl-jaxrs~US616059MultiValue~CI

2023-01-12 12:31 UTC, kploch commented on pom.xml
> +                <version>1.0.0-US616059MultiValue-SNAPSHOT</version>
```suggestion
                <version>1.0.0-SNAPSHOT</version>
```

2023-01-12 12:31 UTC, kploch commented on pom.xml
> +                <version>1.0.0-US616059MultiValue-SNAPSHOT</version>
```suggestion
                <version>1.0.0-SNAPSHOT</version>
```

2023-01-12 12:31 UTC, kploch commented on pom.xml
> +                        <version>1.0.0-US616059MultiValue-SNAPSHOT</version>
```suggestion
                <version>1.0.0-SNAPSHOT</version>
```

2023-01-12 13:24 UTC, dermot-hardy requested changes

2023-01-12 13:24 UTC, dermot-hardy commented on src/main/java/io/github/fileanalysissuite/adaptersdk/impls/jaxrs/FileMetadataImpl.java
> +        final Map<String, Iterable<String>> additionalMetadata = metadata.getAdditionalMetadata().entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
Simplify this in light of interface changes.

2023-01-12 18:05 UTC, dermot-hardy approved these changes

2023-01-12 18:06 UTC, merged